# Generated by Django 4.0.6 on 2022-07-21 03:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visible_for_users',
            field=models.ManyToManyField(blank=True, related_name='visible_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
