# Generated by Django 4.0.6 on 2022-07-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.CharField(max_length=4096, null=True),
        ),
    ]
