# Generated by Django 4.0.6 on 2022-07-21 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_user_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='following',
            new_name='followings',
        ),
    ]
